### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by sunbin1205** [gengyanlei/building_segmentation_dataset#1]
Thank you very much for sharing the data. May I ask if you can provide me with the pictures of other years in the same place for your data? Only a few pictures are enough.

**Comment by sunbin1205** [comment]
I really need a data of two different years with similar distribution of data set published by you. If you have any, please share with me some. This is very important for me.thank you very much！！！

**Comment by gengyanlei** [comment]
@sunbin1205 
您好，（以下是通过baidu translate（百度翻译））。
Sorry, I haven't logged on to GitHub account recently. I just saw your question now.
First of all, to answer your question, I am here to do the direction of remote sensing image semantics segmentation, change detection direction I did not do, but other people in the research group are doing the direction of change detection, the important thing is that they have built the data set, but because our research group itself to use, so can not borrow, I am very sorry.
Secondly, I drew the data by myself, downloaded the images free of charge through special software, but there was no time information. The previous idea was to download SHP from open-map open source image data website to generate label maps, but found many errors, so abandoned.
Finally, it is suggested to purchase relevant images or cooperate with some enterprises to use their image data. Good luck to you!

**Comment by sunbin1205** [comment]
hi,thanks for your share!and i am going to public a paper,which will citie your dataset.thank you again!

**Comment by sunbin1205** [comment]
Are there any formatting requirements for references?

**Comment by gengyanlei** [comment]
@sunbin1205 
Hello, I don't have a paper description for this data set, so I don't have a citation format. If possible, as the third author of the paper you want to write, I will use this data set as a contribution to the paper.
my chinese name is Geng YanLei（耿艳磊），My university is Central South University.
“School of Geosciences and Info-Physics, Central South University, Changsha 410083, China”  This is the English name of my college.

**Comment by gengyanlei** [comment]
@sunbin1205 
这个数据集是我研究生期间10天的成果，虽然我把它绘制出来，但是没有专门撰写一篇论文来描述它，这是我的遗憾。我当时只是拿来做一下实验，但后面它就一直存储在我的电脑中，没有再发挥它的用处，因此上传到GitHub上共享。其实你们可以任意使用，因为我没有引用格式，我提出当作者的要求并不是强求的，你们可以随便使用，可以将我的数据集链接作为一个引用格式。能给其他人带来方便，是我制作这个数据集的贡献。
This data set is the result of my 10-day postgraduate period. Although I have drawn it, I have not written a special paper to describe it. This is my regret. I just took it for an experiment, but it has been stored in my computer since then and has no use for it, so it is uploaded to GitHub for sharing. In fact, you can use it at will, because I do not have a reference format, I do not ask for the author's request, you can use it freely, you can link my data set as a reference format. Neng

**Comment by gengyanlei** [comment]
@sunbin1205 
建议你使用链接作为引用格式。谢谢。
It is recommended that you use links as a reference format. thanks！
